# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run update-readme
    - uses: actions/checkout@v2
    - run: |
        git config user.email marcoseguro2@gmail.com
        git add README.md
        git commit -m "Update README"
        git push origin master
          
    
